from aiogram.types import KeyboardButton,ReplyKeyboardMarkup

absd = ReplyKeyboardMarkup(
    keyboard=[
        [
           KeyboardButton(text="FOTIHA"),
        ],
        [
            KeyboardButton(text="BAQARA"),
        ],
        [
           KeyboardButton(text="IXLOS"),
        ],
        [
            KeyboardButton(text="KAVSAR"),
        ],
        [
            KeyboardButton(text="FALAQ"),
        ],
        [
            KeyboardButton(text="ASR"),
        ],
        [
            KeyboardButton(text="HASHAR"),
        ],
        [
            KeyboardButton(text="NOS"),
        ],
        [
            KeyboardButton(text="AN'OM"),
        ],
        [
            KeyboardButton(text="YASIN"),
        ],
        [
            KeyboardButton(text="MUHAMMAD"),
        ],
        [
            KeyboardButton(text="QADR"),
        ],
        [
            KeyboardButton(text="ZALZAL"),
        ],
        [
            KeyboardButton(text="SHARH"),
        ],
        [
            KeyboardButton(text="QURAYSH"),
        ],
        [
            KeyboardButton(text="MO'UN"),
        ],
        [
            KeyboardButton(text="👈Orqaga qaytish")
        ],
        ],

    resize_keyboard=True
)
